spring.application.name=gestion360-backend

# ========================================
# BASE DE DATOS
# ========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion360
spring.datasource.username=postgres
spring.datasource.password=od290727

# ========================================
# JPA / HIBERNATE
# ========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================================
# SERVIDOR
# ========================================

server.port=8080

# ========================================
# ACTUATOR
# ========================================

management.endpoints.web.exposure.include=health,info